name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Formatting and static analysis
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install prek
        run: uv tool install prek
      - name: Install Javascript dependencies
        run: npm install
      - run: prek run -a

  type-checking:
    name: Type checking
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v6
      - name: Install Javascript dependencies
        run: npm install
      - name: Typecheck TypeScript
        run: npm run typecheck

      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Typecheck Python
        run: uv run --group=dev python -m mypy .

  base-tests:
    name: Tests
    strategy:
      matrix:
        include:
          - { python: '3.11', os: ubuntu-24.04 }
          - { python: '3.11', os: macos-14 }
          - { python: '3.11', os: windows-2025 }
    uses: ./.github/workflows/base-test.yml
    with:
      os-variant: ${{ matrix.os }}
      python-version: ${{ matrix.python }}

  ui-tests:
    name: Tests
    strategy:
      matrix:
        include:
          - { python: '3.11' }
    uses: ./.github/workflows/ui-test.yml
    with:
      python-version: ${{ matrix.python }}

  build:
    name: Build
    strategy:
      matrix:
        include:
          - { python: '3.11' }
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v6
      - name: Install Javascript dependencies
        run: npm install
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Pin Python version
        run: uv python pin ${{ matrix.python }}
      - name: Build package
        run: uv build
